server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
#      default-filters:
#        - AddRequestHeader=Truth, itcast is freaking!!!



