server:
  port: 8081
spring:
  application:
    name: user-service
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true